<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Titan Gaming Desktops</title>

    <link rel="stylesheet" href="styles/style.css">
    <link rel="icon" type="image/png" href="images/logo.png">

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
</head>

<body>

<header>

    <div class="logo">
        <a href="index.php">
            <img src="images/logo.png" alt="Titan Gaming Logo">
        </a>
    </div>

    <div class="header-content">

        <?php include("menu.inc"); ?>

    </div>

</header>