<nav>
    <ul>

        <li>
            <a href="index.php">Home</a>
        </li>

        <li>|</li>

        <li>
            <a href="product.php">Products</a>
        </li>

        <li>|</li>

        <li>
            <a href="payment.php">Payment</a>
        </li>

        <li>|</li>

        <li>
            <a href="about.php">About</a>
        </li>

        <li>|</li>

        <li>
            <a href="enhancements.php">Enhancements</a>
        </li>

        <li>|</li>

        <li>
            <a href="manager.php">Manager</a>
        </li>

    </ul>
</nav>